/* CI-only real-browser / real-Python-worker verification. Keep the Chromium sandbox enabled. */
const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process');
const fs=require('node:fs/promises');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const artifacts=path.resolve(process.env.UI_ARTIFACT_DIR||'test-results/segment-seam-ui');
function startServer(){
 const process=spawn('python',['-m','segment_seam','serve','--no-browser','--port','0'],{cwd:root,stdio:['ignore','pipe','pipe']});
 let log='',error='';process.stderr.on('data',chunk=>{error+=chunk.toString();});
 const ready=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error(`Backend startup timed out: ${log} ${error}`)),15000);process.once('error',failure=>{clearTimeout(timeout);reject(failure);});process.once('exit',code=>{clearTimeout(timeout);reject(new Error(`Backend exited (${code}): ${error}`));});process.stdout.on('data',chunk=>{log+=chunk.toString();const url=log.match(/http:\/\/127\.0\.0\.1:\d+\/[^\s]+\//);if(url){clearTimeout(timeout);resolve(url[0]);}});});
 return {process,ready};
}
async function trackPair(page){await expect(page.locator('#track-section')).toBeVisible();await page.locator('#before-track').selectOption('1');await page.locator('#after-track').selectOption('1');await page.locator('#same-track').check();}
(async()=>{
 await fs.mkdir(artifacts,{recursive:true});const server=startServer();let browser,page;
 try{
  const url=await server.ready;browser=await chromium.launch({headless:true,chromiumSandbox:true});const context=await browser.newContext({viewport:{width:1440,height:1100},reducedMotion:'reduce',acceptDownloads:true});page=await context.newPage();const errors=[],external=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(!request.url().startsWith(url)&&new URL(request.url()).origin!==new URL(url).origin)external.push(request.url());});
  await page.goto(url);await page.locator('#before-file').setInputFiles(path.join(root,'fixtures/before.gpx'));await page.locator('#after-file').setInputFiles(path.join(root,'fixtures/after.gpx'));await expect(page.locator('#inspect-button')).toBeEnabled();await page.locator('#inspect-button').click();await expect(page.locator('#track-section')).toBeVisible();await expect(page.locator('#before-track')).toHaveValue('');await expect(page.locator('#compare-button')).toBeDisabled();await trackPair(page);await page.locator('#compare-button').click();await expect(page.locator('#report-section')).toBeVisible();
  await expect(page.locator('#report-title')).toHaveText('The boundary pattern changed.');await expect(page.locator('.metric-value').first()).toHaveText('2,112.71 m');await expect(page.locator('.seam-row')).toHaveCount(3);await page.locator('.seam-row summary').first().click();await expect(page.locator('.point-card').first()).toContainText('0.001');await expect(page.locator('.point-card').nth(1)).toContainText('0.020');await expect(page.locator('.point-card').first()).toContainText('2026-01-01T00:01:00Z');await page.screenshot({path:path.join(artifacts,'real-desktop-evidence.png'),fullPage:true});
  const packetUrl=new URL(await page.locator('#download-link').getAttribute('href'),url).href;const downloadPromise=page.waitForEvent('download');await page.locator('#download-link').click();const download=await downloadPromise;const packet=path.join(artifacts,'real-evidence.zip');await download.saveAs(packet);
  const inspected=JSON.parse(execFileSync('python',['-c',"import json,sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); j=json.loads(z.read('report.json')); print(json.dumps({'names':z.namelist(),'report':j}))",packet],{encoding:'utf8'}));assert.equal(inspected.report.status,'complete');assert.equal(inspected.report.summary.points,8);assert.equal(inspected.report.summary.removed_boundaries,1);assert.equal(inspected.report.summary.added_boundaries,1);assert.equal(inspected.report.summary.retained_boundaries,1);assert.ok(Math.abs(inspected.report.summary.artificial_distance_m-2112.706524437)<0.001);assert.ok(inspected.names.includes('report.txt') && inspected.names.includes('manifest.json'));
  await page.locator('#lang-ja').click();await page.setViewportSize({width:390,height:844});await page.locator('.seam-row summary').first().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await expect(page.locator('#report-title')).toHaveText('境界の構成が変わりました。');await page.screenshot({path:path.join(artifacts,'real-mobile-japanese.png'),fullPage:true});
  // Replacing a file immediately hides the prior artifact and asks the server to remove it.
  const changed=(await fs.readFile(path.join(root,'fixtures/after.gpx'),'utf8')).replace('lon="0.020"','lon="0.022"');await page.locator('#after-file').setInputFiles({name:'changed-point.gpx',mimeType:'application/gpx+xml',buffer:Buffer.from(changed)});await expect(page.locator('#report-section')).toBeHidden();await expect(page.locator('#download-link')).not.toHaveAttribute('href',/.+/);await expect.poll(async()=> (await fetch(packetUrl)).status).toBe(409);
  await page.locator('#inspect-button').click();await trackPair(page);await page.locator('#compare-button').click();await expect(page.locator('#report-section')).toBeVisible();await expect(page.locator('.unsupported-note')).toBeVisible();await expect(page.locator('.metric')).toHaveCount(0);await expect(page.locator('.seam-row')).toHaveCount(0);assert.match(await page.locator('#download-link').getAttribute('href'),/packet.zip$/);await page.screenshot({path:path.join(artifacts,'real-unsupported.png'),fullPage:true});
  // Reset cancels the latest artifact too; synthetic demo works through the real worker.
  await page.locator('#restart-button').click();await expect(page.locator('#report-section')).toBeHidden();await expect(page.locator('#before-name')).toHaveText('GPX ファイルを選択');await page.locator('#demo-button').click();await expect(page.locator('#track-section')).toBeVisible();await expect(page.locator('#before-track')).toHaveValue('');await expect(page.locator('#same-track')).not.toBeChecked();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS real worker: upload, inspect, explicit pair, exact witnesses, ZIP, Japanese/mobile, stale artifact removal, unsupported, restart, demo');
 }catch(error){if(page)await page.screenshot({path:path.join(artifacts,'real-failure.png'),fullPage:true}).catch(()=>{});throw error;}
 finally{if(browser)await browser.close();server.process.kill('SIGINT');await new Promise(resolve=>{if(server.process.exitCode!==null)return resolve();const timeout=setTimeout(()=>{server.process.kill('SIGKILL');resolve();},3000);server.process.once('exit',()=>{clearTimeout(timeout);resolve();});});}
})().catch(error=>{console.error(error);process.exitCode=1;});
