import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {MAX_FILE_BYTES, fileProblem, formatBytes, validInventory, canCompare, validReport, bytesToBase64, distance, JobRunner, abortableDelay} from '../model.js';
const {inventory,report,unsupported}=createRequire(import.meta.url)('./fixtures.cjs');
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const settle=()=>new Promise(resolve=>setImmediate(resolve));

test('GPX validation enforces extension, nonempty bytes, exact 4 MiB boundary',()=>{
 assert.equal(fileProblem(null),'missing');assert.equal(fileProblem({name:'a.xml',size:3}),'extension');assert.equal(fileProblem({name:'a.gpx',size:0}),'empty');assert.equal(fileProblem({name:'a.gpx',size:NaN}),'empty');assert.equal(fileProblem({name:'A.GPX',size:MAX_FILE_BYTES}),'');assert.equal(fileProblem({name:'a.gpx',size:MAX_FILE_BYTES+1}),'large');
});
test('formatting and base64 preserve literal bytes',()=>{assert.equal(formatBytes(2048),'2 KiB');assert.equal(formatBytes(MAX_FILE_BYTES),'4.0 MiB');assert.equal(bytesToBase64(new Uint8Array([0,127,128,255])),'AH+A/w==');assert.equal(distance(143.735),'143.74 m');});
test('explicit positive indices and affirmation required even for one track',()=>{const data=inventory();assert.equal(canCompare(data,'','',true),false);assert.equal(canCompare(data,'0','1',true),false);assert.equal(canCompare(data,'1','2',false),false);assert.equal(canCompare(data,'1','2',true),true);assert.equal(canCompare(data,'1','9',true),false);assert.equal(canCompare(null,'1','1',true),false);});
test('malformed inventories are rejected',()=>{const data=inventory();assert.equal(validInventory(data),true);data.before.tracks.push(data.before.tracks[0]);assert.equal(validInventory(data),false);assert.equal(validInventory({kind:'inventory'}),false);});
test('complete and unsupported shapes cannot impersonate each other',()=>{assert.equal(validReport(report()),true);assert.equal(validReport(unsupported()),true);const broken=unsupported();broken.summary={};assert.equal(validReport(broken),false);const broken2=report();broken2.seams[0].right_point=4;assert.equal(validReport(broken2),false);const broken3=report();broken3.summary.after_distance_m=Infinity;assert.equal(validReport(broken3),false);});
test('done inspect yields a verified inventory once',async()=>{const updates=[];const runner=new JobRunner({fetcher:async url=>url==='api/jobs'?response({id:'i'}):response({id:'i',status:'done',result:inventory()}),onUpdate:data=>updates.push(data)});await runner.start({mode:'inspect'});assert.deepEqual(updates.map(v=>v.status),['running','done']);});
test('malformed done result is an error without a report',async()=>{const updates=[];const runner=new JobRunner({fetcher:async url=>url==='api/jobs'?response({id:'i'}):response({id:'i',status:'done',result:{}}),onUpdate:data=>updates.push(data)});await runner.start({mode:'inspect'});assert.equal(updates.at(-1).status,'error');assert.equal(updates.at(-1).error,'Incomplete worker result');});
test('worker errors and cancellations terminate polling',async()=>{for(const status of ['error','cancelled']){const updates=[];let polls=0;const runner=new JobRunner({fetcher:async url=>url==='api/jobs'?response({id:'j'}):(polls++,response({id:'j',status,error:'worker stopped'})),onUpdate:d=>updates.push(d)});await runner.start({mode:'compare'});assert.equal(polls,1);assert.equal(updates.at(-1).status,status);}});
test('start HTTP error and missing ID are surfaced without polling',async()=>{for(const reply of [response({error:'File too large'},413),response({})]){const updates=[];const runner=new JobRunner({fetcher:async()=>reply,onUpdate:d=>updates.push(d)});await runner.start({mode:'inspect'});assert.equal(updates.at(-1).status,'error');}});
test('unknown statuses and mismatched IDs never expose results',async()=>{for(const payload of [{id:'wrong',status:'done',result:report()},{id:'j',status:'surprise'}]){const updates=[];const runner=new JobRunner({fetcher:async url=>url==='api/jobs'?response({id:'j'}):response(payload),onUpdate:d=>updates.push(d)});await runner.start({mode:'compare'});assert.equal(updates.at(-1).status,'error');}});
test('cancel before start response awaits ID and cancels stale job',async()=>{const start=deferred(),calls=[],updates=[];const runner=new JobRunner({fetcher:async(url,options)=>{calls.push([url,options]);return url==='api/jobs'?start.promise:response({id:url.split('/')[2],status:'cancelled'});},onUpdate:d=>updates.push(d)});const work=runner.start({mode:'inspect'});await settle();const cancelled=runner.cancel();start.resolve(response({id:'late'}));await Promise.all([work,cancelled]);assert.deepEqual(calls.map(c=>c[0]),['api/jobs','api/jobs/late/cancel']);assert.equal(updates.length,0);assert.equal(calls[0][1].signal,undefined);assert.equal(calls[1][1].keepalive,true);});
test('late cancelled POST is cleaned before a newer POST starts',async()=>{const gate=deferred(),calls=[],updates=[];let posts=0;const runner=new JobRunner({fetcher:async url=>{calls.push(url);if(url==='api/jobs'){posts++;return posts===1?gate.promise:response({id:'new'});}if(url.endsWith('/cancel'))return response({id:url.split('/')[2],status:'cancelled'});return response({id:'new',status:'done',result:inventory()});},onUpdate:d=>updates.push(d)});const old=runner.start({mode:'inspect'});await settle();runner.cancel();const fresh=runner.start({mode:'inspect'});await settle();assert.equal(posts,1);gate.resolve(response({id:'old'}));await Promise.all([old,fresh]);assert.deepEqual(calls,['api/jobs','api/jobs/old/cancel','api/jobs','api/jobs/new']);assert.equal(updates.at(-1).id,'new');});
test('poll abort and out-of-order stale completion are both ignored',async()=>{const poll=deferred(),updates=[];let signal;const runner=new JobRunner({fetcher:async(url,options)=>{if(url==='api/jobs')return response({id:'j'});if(url.endsWith('/cancel'))return response({id:url.split('/')[2],status:'cancelled'});signal=options.signal;return poll.promise;},onUpdate:d=>updates.push(d)});const job=runner.start({mode:'compare'});await settle();await runner.cancel();assert.equal(signal.aborted,true);poll.resolve(response({id:'j',status:'done',result:report()}));await job;assert.deepEqual(updates.map(v=>v.status),['running']);});
test('completed jobs are explicitly cancelled to delete downloads',async()=>{const calls=[];const runner=new JobRunner({fetcher:async url=>{calls.push(url);return url==='api/jobs'?response({id:'j'}):url.endsWith('/cancel')?response({id:url.split('/')[2],status:'cancelled'}):response({id:'j',status:'done',result:report()});}});await runner.start({mode:'compare'});await runner.cancel();assert.equal(calls.at(-1),'api/jobs/j/cancel');});
test('cancellation failure blocks subsequent starts rather than orphaning work',async()=>{const updates=[];let posts=0;const runner=new JobRunner({fetcher:async url=>{if(url==='api/jobs'){posts++;return response({id:'j'});}if(url.endsWith('/cancel'))return response({},500);return response({id:'j',status:'done',result:report()});},onUpdate:d=>updates.push(d)});await runner.start({mode:'compare'});await assert.rejects(runner.cancel(),/Cancel failed/);await runner.start({mode:'inspect'});assert.equal(posts,1);assert.equal(updates.at(-1).status,'error');});
test('cancelling before queued start issues no POST',async()=>{let calls=0;const runner=new JobRunner({fetcher:async()=>{calls++;return response({id:'j'});}});const work=runner.start({mode:'inspect'});await runner.cancel();await work;assert.equal(calls,0);});
test('abortable sleep aborts immediately and does not busy-poll',async()=>{const controller=new AbortController();const sleeping=abortableDelay(5000,controller.signal);controller.abort();await assert.rejects(sleeping,{name:'AbortError'});await assert.rejects(abortableDelay(1,controller.signal),{name:'AbortError'});});


test('all partial or incoherent successful reports fail closed',()=>{
 const corruptions=[r=>{r.witnesses_truncated=true;},r=>{delete r.witnesses_truncated;},r=>{r.summary.removed_boundaries=0.5;},r=>{r.summary.added_boundaries=-1;},r=>{r.summary.retained_boundaries=99;},r=>{r.summary.before_distance_m=-1;},r=>{r.summary.points=7;},r=>{r.before.sha256='missing';},r=>{r.after.bytes=0;},r=>{r.method.radius_m=0;},r=>{r.scope=[null];},r=>{r.metadata_note=null;},r=>{r.seams[0].left.index=1;},r=>{r.seams[0].after.right_segment=2;},r=>{r.seams.reverse();},r=>{r.seams[0].distance_m=-1;},r=>{r.summary.artificial_distance_m=1;},r=>{r.summary.net_distance_change_m=1;},r=>{r.verdict='boundaries_unchanged';},r=>{r.seams[0].left.time={state:'raw'};}];
 for(const corrupt of corruptions){const value=report();corrupt(value);assert.equal(validReport(value),false,corrupt.toString());}
});
test('raw empty/whitespace values and absent fields remain legal and distinct',()=>{const value=report();value.seams[0].left.time={state:'raw',text:''};value.seams[0].right.time={state:'raw',text:' \n '};value.seams[0].left.elevation={state:'absent'};assert.equal(validReport(value),true);});

test('cancellation requires exact job ID, cancelled state, and absent report',async()=>{
 for(const body of [{id:'j',status:'running'},{id:'other',status:'cancelled'},{id:'j',status:'cancelled',result:report()},{status:'cancelled'}]){
  const runner=new JobRunner({fetcher:async()=>response(body)});await assert.rejects(runner.cancelRemote('j'),/not confirmed/);
 }
});
test('already absent cancellation is successful without a JSON body',async()=>{const runner=new JobRunner({fetcher:async()=>({ok:false,status:404,json:()=>{throw new Error('Must not read absent response');}})});await runner.cancelRemote('gone');});
